/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List news items */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["NewsItem"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a news item (admin only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewsItemCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            id: string;
                        };
                    };
                };
                401: components["responses"]["NotAuthenticated"];
                403: components["responses"]["AdminRequired"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news?id={id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a news item (admin only) */
        delete: {
            parameters: {
                query: {
                    id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                401: components["responses"]["NotAuthenticated"];
                403: components["responses"]["AdminRequired"];
            };
        };
        options?: never;
        head?: never;
        /** Update a news item (admin only) */
        patch: {
            parameters: {
                query: {
                    id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewsItemUpdate"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
                401: components["responses"]["NotAuthenticated"];
                403: components["responses"]["AdminRequired"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/committee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List committee members */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["CommitteeMember"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create committee member (admin only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommitteeMemberCreate"];
                };
            };
            responses: {
                201: components["responses"]["CreatedWithId"];
                401: components["responses"]["NotAuthenticated"];
                403: components["responses"]["AdminRequired"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/committee?id={id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete committee member (admin only) */
        delete: {
            parameters: {
                query: {
                    id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                401: components["responses"]["NotAuthenticated"];
                403: components["responses"]["AdminRequired"];
            };
        };
        options?: never;
        head?: never;
        /** Update committee member (admin only) */
        patch: {
            parameters: {
                query: {
                    id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommitteeMemberUpdate"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
                401: components["responses"]["NotAuthenticated"];
                403: components["responses"]["AdminRequired"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List team sections and teams */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            sections: components["schemas"]["TeamSection"][];
                            teams: components["schemas"]["Team"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create team section or team (admin only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TeamSectionCreate"] | components["schemas"]["TeamCreate"];
                };
            };
            responses: {
                201: components["responses"]["CreatedWithId"];
                401: components["responses"]["NotAuthenticated"];
                403: components["responses"]["AdminRequired"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams?type={type}&id={id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a team section or team (admin only) */
        delete: {
            parameters: {
                query: {
                    type: "section" | "team";
                    id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                401: components["responses"]["NotAuthenticated"];
                403: components["responses"]["AdminRequired"];
            };
        };
        options?: never;
        head?: never;
        /** Update a team section or team (admin only) */
        patch: {
            parameters: {
                query: {
                    type: "section" | "team";
                    id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TeamSectionUpdate"] | components["schemas"]["TeamUpdate"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
                401: components["responses"]["NotAuthenticated"];
                403: components["responses"]["AdminRequired"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        NewsItem: {
            id: string;
            title: string;
            text: string;
            body?: string | null;
            link: string;
            linkText: string;
            sections?: string[] | null;
            createdAt: number;
            updatedAt: number;
        };
        NewsItemCreate: {
            title?: string;
            text?: string;
            body?: string;
            link?: string;
            linkText?: string;
            sections?: string[];
        };
        NewsItemUpdate: {
            title?: string;
            text?: string;
            body?: string | null;
            link?: string;
            linkText?: string;
            sections?: string[] | null;
        };
        CommitteeMember: {
            id: string;
            role: string;
            name: string;
            contact: string;
            sortOrder: number;
            createdAt: number;
            updatedAt: number;
        };
        CommitteeMemberCreate: {
            role: string;
            name?: string;
            contact?: string;
            sortOrder?: number;
        };
        CommitteeMemberUpdate: {
            role?: string;
            name?: string;
            contact?: string;
            sortOrder?: number;
        };
        TeamSection: {
            id: string;
            sectionKey: string;
            name: string;
            subtitle: string;
            icon: string;
            logo?: string | null;
            sortOrder: number;
            createdAt: number;
            updatedAt: number;
        };
        Team: {
            id: string;
            sectionId: string;
            name: string;
            description: string;
            manager: string;
            coach: string;
            contact: string;
            photo?: string | null;
            slug?: string | null;
            sidebar: number;
            managerLabel?: string | null;
            coachLabel?: string | null;
            sortOrder: number;
            createdAt: number;
            updatedAt: number;
        };
        TeamSectionCreate: {
            /** @enum {string} */
            type: "section";
            sectionKey: string;
            name: string;
            subtitle?: string;
            icon?: string;
            logo?: string;
            sortOrder?: number;
        };
        TeamCreate: {
            /** @enum {string} */
            type: "team";
            sectionId: string;
            name: string;
            description?: string;
            manager?: string;
            coach?: string;
            contact?: string;
            photo?: string;
            slug?: string;
            sidebar?: boolean;
            managerLabel?: string;
            coachLabel?: string;
            sortOrder?: number;
        };
        TeamSectionUpdate: {
            sectionKey?: string;
            name?: string;
            subtitle?: string;
            icon?: string;
            logo?: string | null;
            sortOrder?: number;
        };
        TeamUpdate: {
            sectionId?: string;
            name?: string;
            description?: string;
            manager?: string;
            coach?: string;
            contact?: string;
            photo?: string | null;
            slug?: string | null;
            sidebar?: boolean;
            managerLabel?: string | null;
            coachLabel?: string | null;
            sortOrder?: number;
        };
    };
    responses: {
        /** @description OK */
        Ok: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    ok: boolean;
                };
            };
        };
        /** @description Created */
        CreatedWithId: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    ok: boolean;
                    id: string;
                };
            };
        };
        /** @description Not authenticated */
        NotAuthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Admin access required */
        AdminRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
